[build]
  command = "npm run build"
  publish = "dist"
  functions = "dist"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/api/*"
  to = "/:splat"
  status = 200

[functions]
  node_bundler = "esbuild"